#include <iostream>
#include <fstream>
#include <vector>
#include <algorithm>
#include <map>
#include <set>
#include <unordered_set>
#include <unordered_map>
#include <queue>
#include <stack>
#include <cstring>
#include <iterator>
#include <chrono>
#include <ctime>
#include <sstream>
#include <cmath>
#include <cctype>
#include <tuple>